
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Latest compiled and minified CSS -->


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Visit.com</title>
   <!-- -->
    <!-- core CSS -->
    <script src="/js/jquery-1.12.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>

    <link href="/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-theme.min.css.map" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/bootstrap/css/datepicker.css">
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap.css.map" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-theme.css" rel="stylesheet">

    <style>
        body { padding-top: 70px;
                padding-bottom: 30px;
                padding-left: 20px;
                padding-right: 20px;
                                }
    </style>

    <link rel="stylesheet" href="/css/slicknav.css">
        <link rel="stylesheet" href="/css/owl.theme.css">
        <link rel="stylesheet" href="/css/owl.carousel.css">
        <link rel="stylesheet" href="/css/owl.transitions.css">
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/css/responsive.css">
        <script src="/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="/js/owl.carousel.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/plugins.js"></script>
        <script src="/js/main.js"></script>
         <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>

<body>
<nav class="navbar  bg-info navbar-fixed-top">

    <div class="container-fluid" >
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/user/home"><span class="glyphicon glyphicon-home"></span> bonne nuit </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

         

             

<?php
    $auth = Zend_Auth::getInstance();
    $storage = $auth->getStorage();
    $adminsession = new Zend_Session_Namespace('admin_Auth');
    $sessionRead = $storage->read();
    $fbsession = new Zend_Session_Namespace('facebook');
if (!empty($sessionRead)) {
        $name = $sessionRead->username; ?>


            <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle2" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">COUNTRIES<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <?php
            foreach ($this->countries as $key => $value)
            { 
                echo "<li><a href='/user/listcountry/id/{$value['id']}'>{$value['name']}</a></li><li role='separator'class='divider'></li>";
             }?>
          </ul>
        </li>
      </ul>
     <ul class="nav navbar-nav navbar-right "><!-- right side data -->
         <li>
             <a class="navbar-brand" > Welcome <?=$name?></a>
         </li>
         <li>
             <a  href="/user/get-reservations"> <i class="glyphicon glyphicon-user"></i>Your Hotel Reservations </a>
         </li>
         <li><a  href="/user/get-car-reservation"><i class="glyphicon glyphicon-user"></i> Your Car Rents </a></li>
        <li class="dropdown">
            <a class="btn btn-primary navbar-btn" href="<?php echo $this->baseUrl() ?>/User/logout"> <span class="glyphicon glyphicon-log-out"> Logout </a>
        </li>
      </ul>
<?php
    }
    elseif (isset($fbsession->first_name) && !empty (isset($fbsession->first_name))) {
        $name = $fbsession->first_name;?>
        <ul class="nav navbar-nav navbar-right"><!-- right side data -->
            <li><a class="navbar-brand"> Welcome <?=$name?></a></li>
            <li class="dropdown">
                <a class="btn btn-primary navbar-btn" href="<?php echo $this->baseUrl() ?>/User/fblogout"> Logout </a>
            </li>
        </ul>
<?php
}

elseif (isset($adminsession->first_name) && !empty (isset($adminsession->first_name))) {
        $name = $adminsession->first_name;
        echo "Welcome " . $name->name;
        //var_dump($name);
        ?>

            <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle2" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">COUNTRIES<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <?php
            foreach ($this->countries as $key => $value)
            { 
                echo "<li><a href='/admin/onecountry/id/{$value['id']}'>{$value['name']}</a></li><li role='separator'class='divider'></li>";
             }?>
          </ul>
        </li>
      </ul>
        <a class="btn btn-default  navbar-btn" href="<?php echo $this->baseUrl() ?>/admin/logout">
        Logout </a>

<?php
}
?>
            </div> <!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
</body>

<?php echo $this->layout()->content; ?>

<section id="footercopy">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <div class="copyright">
      <p> &copy; Copyright 2015. Designed by <a href="/user/home">KGAR</a></p>
    </div>
                        </div>
                    </div><!-- col-md-12 -->
                </div><!-- .row -->
            </div><!-- .container -->
        </section><!-- #footer -->

