<br /><br />
<div id="view-content">
	
	<!-- <?php
// 		foreach ($this->city as $key => $value)
// 		{
			
// echo $value['id'] ;
// echo "<br>";
// echo  $value['name'];
// echo "<br>";
// echo "<img src='{$value['image']}'>";
// echo "<br>";
// echo $value['rating'] ;
// echo "<br>";
// echo $value['description'] ; 


// 		}
	?> -->

<div class="jumbotron">
      <div class="container">
      <?php
			foreach ($this->city as $key => $value)
			{ 
        echo "<h1>{$value['name']}</h1>
        <p><img src='{$value['image']}' width='1200' height='300'class='img-rounded'></p>
        <p>{$value['description']}</p>";
        }?>
      </div>
    </div>
    
    <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <div class="footer-contant">
                                
                                <div class="support-link">
                                    <ul>
                                        <li><a href="/user/postr/">EXPERIENCE</a></li>
                                        <li><a href="#">HOTEL</a></li>
                                        <li><a href="/user/map/">MAP</a></li>
                                        <li><a href="#">BOOKED-HOTEL</a></li>
                                        <li><a href="#">BOOKED-CARS</a></li>
                                        <li><a href="/user/showlocations/">LOCATIONS</a></li>
                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div><!-- col-md-12 -->
                </div><!-- .row -->
            </div><!-- .container -->
        </section><!-- #footer -->
	
</div>