<br /><br />
<div id="view-content">
	
	<!-- <?php
// 		foreach ($this->city as $key => $value)
// 		{
			
// echo $value['id'] ;
// echo "<br>";
// echo  $value['name'];
// echo "<br>";
// echo "<img src='{$value['image']}'>";
// echo "<br>";
// echo $value['rating'] ;
// echo "<br>";
// echo $value['description'] ; 


// 		}
	?> -->

<div class="jumbotron">
      <div class="container">
      <?php
			foreach ($this->city as $key => $value)
			{ 
        echo "<h1>{$value['name']}</h1>
        <p><img src='{$value['image']}' width='1200' height='300'class='img-rounded'></p>
        <p>{$value['description']}</p>";
        }?>
      </div>
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
      <div class="container">
        <div class="navbar-footer">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/user/postr/id/<?= $value['id'] ?>">EXPERIENCES</a>
          <a class="navbar-brand" href="/user/map/id/<?= $value['id'] ?>">MAP</a>
          <a class="navbar-brand" href="/user/showlocations/id/<?= $value['id'] ?>">LOCATIONS</a>
            <?php $user=$this->user; ?>
            <?php if($user){ ?>
                <a class="navbar-brand" href="">My BooKing</a>
                <a class="navbar-brand" href="/user/make-Reservation/cid/<?= $value['id'] ?>">Book hotel</a>
                <a class="navbar-brand" href="/user/make-car-reserv/id/<?= $value['id'] ?>">Rent cars</a>
            <?php } ?>
        </div>
        
      </div>
    </nav>
	
</div>