<br /><br />
<div id="view-content">
	
	<!-- <?php
// 		foreach ($this->city as $key => $value)
// 		{
			
// echo $value['id'] ;
// echo "<br>";
// echo  $value['name'];
// echo "<br>";
// echo "<img src='{$value['image']}'>";
// echo "<br>";
// echo $value['rating'] ;
// echo "<br>";
// echo $value['description'] ; 


// 		}
	?> -->

<div class="jumbotron">
      <div class="container">
      <?php
			foreach ($this->city as $key => $value)
			{ 
        echo "<h1>{$value['name']}</h1>
        <p><img src='{$value['image']}' width='1200' height='300'class='img-rounded'></p>
        <p>{$value['description']}</p>";
        }?>
      </div>
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
      <div class="container">
        <div class="navbar-footer">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">EXPERIENCES</a>
          <a class="navbar-brand" href="#">HOTEL</a>
          <a class="navbar-brand" href="#">MAP</a>
          <a class="navbar-brand" href="#">BOOKED-HOTEL</a>
          <a class="navbar-brand" href="#">BOOKED-cars</a>
          <a class="navbar-brand" href="#">LOCATIONS</a>
          <a class="navbar-brand" href="#">Description</a>
        </div>
        
      </div>
    </nav>
	
</div>