
<h1 align="center">
	Hotel Reservation
</h1>
 
<?php
echo $this->hotelreservform;
// echo $this->hotelreservform->getElement('name');
// echo'<br/>';
// echo $this->hotelreservform->getElement('from');
// echo'<br/>';
// echo $this->hotelreservform->getElement('to');
// echo'<br/>';
// echo $this->hotelreservform->getElement('member');
// echo'<br/>';
// echo $this->hotelreservform->getElement('submit');
// echo'<br/>';
?>
 
<script>

	$('#from_field').datepicker('hide');
	$('#to_field').datepicker('hide');

</script>