<?php
$city = $this->city;
//var_dump($city);
$longitude = $city[0]['Longitude'];
//var_dump($longitude);
$latitude = $city[0]['Latitude'];
//var_dump( $longitude);
?>
<html>
<head>
	<style>
		#map {
			width: 500px;
			height: 400px;
			align-content: center;
		}
	</style>
</head>
<body>
<div id="map"></div>
<script>
	function initMap() {
		var mapDiv = document.getElementById('map');
		var map = new google.maps.Map(mapDiv, {
			center: {lat:<?= $latitude ?> , lng:  <?= $longitude ?> },
			zoom: 8
		});
	}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
		async defer></script>
</body>
</html>
