<html>
<head>
	<style>
		#map {
			width: 500px;
			height: 400px;
			align-content: center;
		}
	</style>
</head>
<body>
<div id="map"></div>
<script>
	function initMap() {
		var mapDiv = document.getElementById('map');
		var map = new google.maps.Map(mapDiv, {
			center: {lat: <?php 44.540?>, lng: <?php -78.546 ?>},
			zoom: 8
		});
	}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
		async defer></script>
</body>
</html>
