<?php $user=$this->user ?>
<div class='row'>
<?php foreach ($this->pos as $post) { ?>
			<div class='container-fluid'>
			
			<div class='col-xs-8'>
				<div class='container post'>
					<!-- experience -->

						<h1> <?= $post['title'] ?> </h1>
						<h3> <?= $post['content'] ?></h3>
						<?php $post_id= $post['id']; ?>
						<input type='hidden' id='pid' value='<?= $post_id?>'>
						<?php if($post['user_id']== $user ){ ?>
							<a class='btn btn-danger' href='/user/postdelete/id/<?= $post['id'] ?> '>delete</a>
							<a class='btn btn-warning' href='/user/postupdate/id/<?= $post['id'] ?> '>Update</a>
							<?php } ?>

						<!--//// when only login -->
							<br/><a class='btn btn-success addcom' id='<?= $post_id ?>' >ADD COMMENT</a>
							<br/><input datatype='text' size='50px' width='100px' id='comment'>
						<!-- } -->
					</div>

					<!-- comments with delete and update -->
				<div class='container maincomment' id='maincomment'>
					<?php foreach ($this->com as $comment) {
						if($post['id']== $comment['post_id']) { ?>
								<h5>  <?= $comment['content'] ?> </h5>
								<?php $comment_id= $comment['id']; ?>
								<input type='hidden' id='cid' value='<?= $comment_id ?> '>

							<a class='btn btn-danger' href='/user/commentdelete/id/<?= $comment['id']?> '>delete</a>
							<?php } ?>
						<?php } ?>
				</div>
			</div>
			</div>
			</div>
<?php } ?>

<script src="/jquery-1.12.1.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/comment.js"></script>