<?php
	foreach ($this->paginator as $location) { ?>
		<div class='container-fluid table-responsive' align="center">
			<table class="table-responsive">
				<tr>
					<td>
						<h1 align='center'> <?=  $location['name'] ?> </h1>
					</td>
				</tr>
				<tr>
					<td>
						<img align="center" src="<?= $location['image'] ?>"   border=0 width=677 height=192>
					</td>
				</tr>
				<tr>
					<td>
						<h3 align='center'> <?= $location['describtion'] ?> </h3>
					</td>
				</tr>
				</table>
		</div>
	<?php } ?>

<?php echo $this->paginator;?>
