<br /><br />
<div id="view-content">
	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>rate</th>
			<th>description</th>
		</tr>
	</thead>
	<?php
		foreach ($this->cities as $key => $value)
		{
			echo "<tr class='table-responsive'>".
"<td>" . $value['id'] . "</td>" .
"<td>" . $value['name'] . "</td>" .
"<td>" . $value['rating'] . "</td>" .
"<td>" . $value['description'] . "</td>" .
"<td> <a href='/admin/onecity/id/".$value['id']."'class='btn btn-primary'> city details </a> </td>" .
"<td> <a href='/admin/editcity/id/".$value['id']."'class='btn btn-warning'> update</a> </td>".
"<td> <a href='/admin/removecity/id/".$value['id']."'class='btn btn-danger'> Delete </a> </td>".
"<td> <a href='/admin/addlocation/id/".$value['id']."'class='btn btn-success'> Add location </a> </td>".
"<td> <a href='/admin/gethotels/id/".$value['id']."'class='btn btn-success'> Hotels </a> </td>".
"</tr>";
		}
	?>
	</table>
</div>