<br /><br />
<div id="view-content">
	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>rate</th>
			<th>description</th>
		</tr>
	</thead>
	<?php
		foreach ($this->countries as $key => $value)
		{
			echo "<tr>".
"<td>" . $value['id'] . "</td>" .
"<td>" . $value['name'] . "</td>" .
"<td>" . $value['rating'] . "</td>" .
"<td>" . $value['description'] . "</td>" .
"<td> <a href='onecountry/id/ ".$value['id']."'class='btn btn-primary'> country details </a> </td>" .
"<td> <a href='allcity/id/".$value['id']."'class='btn btn-warning'> country city</a> </td>".
"<td> <a href='editcountry/id/".$value['id']."'class='btn btn-warning'> update</a> </td>".
"<td> <a href='addcountry/id/".$value['id']."'class='btn btn-warning'> add country</a> </td>".
"<td> <a href='addcity/id/".$value['id']."'class='btn btn-warning'> add city</a> </td>".
"<td> <a href='removecountry/id/".$value['id']."'class='btn btn-danger'> Delete </a> </td>"

."</tr>";
		}
	?>
	</table>

</div>