<br /><br />
<div id="view-content">
	<p>View script for controller <b>Visit</b> and script/action name <b>gethotels</b></p>
</div>
<?php
print_r($this->hotels);
?>
<table border="1" class="table table-striped table-bordered table-hover">
	<tr>
		<th>
			hotel name
		</th>
		<th>
			hotel address
		</th>
		<th>
			hotel email
		</th>
		<th>
			hotel phone
		</th>
		<th>
			hotel rate
		</th>
		<th>
			hotel city
		</th>
		<th colspan="2">
		</th>

	</tr>
	<?php
	foreach($this->hotels as $key=>$hotel)
	{
		echo"<tr>";
		echo "<td>";
		echo $hotel['name'];
		echo "</td>";
		echo "<td>";
		echo $hotel['address'];
		echo "</td>";
		echo "<td>";
		echo $hotel['email'];
		echo "</td>";
		echo "<td>";
		echo $hotel['phone'];
		echo "</td>";
		echo "<td>";
		echo $hotel['rate'];
		echo "</td>";
		echo "<td>";
		echo $hotel['city_id'];
		echo "</td>";
		echo "<td>";
		echo "<a class='btn btn-warning' href='updatehotel/id/".$hotel['id']."'> Edit </a>";
		echo "</td>";
		echo "<td>";
		echo "<a class='btn btn-danger' href='deletehotel/id/".$hotel['id']."'> Delete </a>";
		echo "</td>";
		echo "</tr>";
	}
	?>
</table>